/*
 * ta-solve
 *
 * The unnamed Tin Arm solver API
 *
 * API version: 1.0
 * Contact: api@tinarmengineering.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"

	sw "github.com/tinarmengineering/tinarm-api-srv/go"
)

func main() {
	router := sw.NewRouter()
	log.Fatal(router.Run(":8080"))
}
