/*
 * ta-solve
 *
 * The unnamed Tin Arm solver API
 *
 * API version: 1.0
 * Contact: api@tinarmengineering.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	sw "github.com/tinarmengineering/tinarm-api-srv/go"
	dbo "github.com/tinarmengineering/tinarm-api-srv/go/dbo"
	//
	//sw "./go"
)

func main() {

	dbo.ConnectDatabase()

	log.Printf("Server started")

	router := sw.NewRouter()

	log.Fatal(router.Run(":8080"))
}
