/*
 * ta-solve
 *
 * The unnamed Tin Arm solver API
 *
 * API version: 1.0
 * Contact: api@tinarmengineering.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"

	"github.com/gin-gonic/gin"
)

// DeleteJobsId - Delete Job
func DoDeleteJobsId(c *gin.Context) {

	// var job dbo.Job
	// dbo.DB.Delete(&job, c.Param("id"))

	// c.JSON(http.StatusOK, gin.H{})
}

// GetJobsId - Get Job
func DoGetJobsId(c *gin.Context) {

	// var job dbo.Job
	// dbo.DB.First(&job, c.Param("id"))

	// if job.ID == 0 {
	// 	c.JSON(http.StatusNotFound, gin.H{})
	// } else {
	// 	c.JSON(http.StatusOK, job)
	// }
}

// PostRectanglejobs - Create RectangleJob
func DoPostRectanglejobs(c *gin.Context) {

	var rJob Rectanglejob
	err := c.BindJSON(&rJob)
	if err != nil {
		c.JSON(http.StatusBadRequest, err)
		return
	}

	insertJobResult, err := Database{}.InsertOne("jobs", rJob)
	if err != nil {
		c.JSON(http.StatusInternalServerError, err)
		return
	}

	rJobGeomotry, err := json.Marshal(rJob.Geometry)
	if err != nil {
		c.JSON(http.StatusBadRequest, err)
		return
	}

	body := "{\"id\":\"" +
		insertJobResult +
		"\", \"data\":" +
		string(rJobGeomotry) +
		", \"nextstep\":null}"

	Enqueue(body)

	c.JSON(http.StatusOK, rJob)
}

// PostStatorjobs - Create StatorJob
func DoPostStatorjobs(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PutMaterialsId - Update Materials
func DoPutMaterialsId(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// DoDeleteMaterialsId - Update Materials
func DoDeleteMaterialsId(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// DoGetMaterialsId - Update Materials
func DoGetMaterialsId(c *gin.Context) {

	material, err := GetMaterialById(c.Param("id"))
	if err == nil {
		c.JSON(http.StatusOK, material)
	} else {
		c.JSON(http.StatusNotFound, err)
	}
	c.JSON(http.StatusOK, "material")
}

func DoPostMaterials(c *gin.Context) {
	var material Material
	err := c.BindJSON(&material)
	if err != nil {
		c.JSON(http.StatusBadRequest, err)
		return
	}

	insertMaterialResult, err := Database{}.InsertOne("materials", material)
	if err != nil {
		c.JSON(http.StatusInternalServerError, err)
		return
	}

	var materialId interface{} = insertMaterialResult
	material.Id = &materialId

	c.JSON(http.StatusOK, material)
}
