/*
 * ta-solve
 *
 * The unnamed Tin Arm solver API
 *
 * API version: 1.0
 * Contact: api@tinarmengineering.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

// DeleteJobsId - Delete Job
func DeleteJobsId(c *gin.Context) {
	DoDeleteJobsId(c)
}

// GetJobsId - Get Job
func GetJobsId(c *gin.Context) {
	DoGetJobsId(c)
}

// PostRectanglejobs - Create RectangleJob
func PostRectanglejobs(c *gin.Context) {
	DoPostRectanglejobs(c)
}

// PostStatorjobs - Create StatorJob
func PostStatorjobs(c *gin.Context) {
	DoPostStatorjobs(c)
}
