/*
 * ta-solve
 *
 * The unnamed Tin Arm solver API
 *
 * API version: 1.0
 * Contact: api@tinarmengineering.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Statorgeometry - The stator geometry for this job 
type Statorgeometry struct {

	// Stator bore (mm)
	Bore *interface{} `json:"bore"`

	// Tooth tip depth (mm)
	ToothTipDepth *interface{} `json:"tooth_tip_depth"`

	// Slot opening (mm)
	SlotOpening *interface{} `json:"slot_opening"`

	// Tooth width (mm)
	ToothWidth *interface{} `json:"tooth_width"`

	// Stator outer diameter (mm)
	OuterDiameter *interface{} `json:"outer_diameter"`

	// Back iron thickness (mm)
	BackIronThickness *interface{} `json:"back_iron_thickness"`

	// Internal redius (mm)
	InternalRadius *interface{} `json:"internal_radius"`

	// Number of slots
	NumberSlots *interface{} `json:"number_slots"`

	// Tool tip angle (degrees)
	ToothTipAngle *interface{} `json:"tooth_tip_angle"`
}
