/*
 * ta-solve
 *
 * The unnamed Tin Arm solver API
 *
 * API version: 1.0
 * Contact: api@tinarmengineering.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Statorjob - Represents a stator job resource
type Statorjob struct {

	Geometry Statorgeometry `json:"geometry"`
}
