/*
 * ta-solve
 *
 * The unnamed Tin Arm solver API
 *
 * API version: 1.0
 * Contact: api@tinarmengineering.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Job - Represents a basic job resource
type Job struct {

	Id *interface{} `json:"id,omitempty"`

	Status *interface{} `json:"status,omitempty"`

	OriginalJob *interface{} `json:"originalJob,omitempty"`
}
