/*
 * ta-solve
 *
 * The unnamed Tin Arm solver API
 *
 * API version: 1.0
 * Contact: api@tinarmengineering.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Rectanglejob - Represents a rectangle job resource
type Rectanglejob struct {

	Geometry Rectanglegeometry `json:"geometry"`
}
