/*
 * ta-solve
 *
 * The unnamed Tin Arm solver API
 *
 * API version: 1.0
 * Contact: api@tinarmengineering.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Rectanglegeometry - The rectangle geometry for this job 
type Rectanglegeometry struct {

	// Length (mm)
	Length *interface{} `json:"length"`

	// Width (mm)
	Width *interface{} `json:"width"`
}
