/*
 * ta-solve
 *
 * The unnamed Tin Arm solver API
 *
 * API version: 1.0
 * Contact: api@tinarmengineering.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Statorjob - Represents a stator job resource
type Statorjob struct {

	Geometry Statorgeometry `json:"geometry"`
}

// AssertStatorjobRequired checks if the required fields are not zero-ed
func AssertStatorjobRequired(obj Statorjob) error {
	elements := map[string]interface{}{
		"geometry": obj.Geometry,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertStatorgeometryRequired(obj.Geometry); err != nil {
		return err
	}
	return nil
}

// AssertRecurseStatorjobRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Statorjob (e.g. [][]Statorjob), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseStatorjobRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aStatorjob, ok := obj.(Statorjob)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertStatorjobRequired(aStatorjob)
	})
}
